package com.vocably.common.error;

public enum ErrorCode {

    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    INVALID_PARAMETER,

    UNAUTHORIZED,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    REFRESH_TOKEN_MISSING,

    FORBIDDEN,

    NOT_FOUND,
    ENDPOINT_NOT_FOUND,

    METHOD_NOT_ALLOWED,

    CONFLICT,
    EMAIL_ALREADY_USED,
    LANGUAGE_ALREADY_EXISTS,

    NOT_IMPLEMENTED,

    INTERNAL_ERROR
}
